### ISSUE TITLE
parytyId 가 먼가여 

### ISSUE THREAD

**Issue by wkdtndgns** [shouwn/graduation.skhu.net-back#31]
@PutMapping("{partyId}")
    @Secured("ROLE_ADMIN")
    fun updateParty(@CurrentUser user: UserPrincipal,
                    @PathVariable("partyId") partyId: Long,
                    @RequestBody partyRequest: PartyRequest) =
            ResponseEntity.ok(partyService.updateParty(user, partyId, partyRequest))

**Comment by shouwn** [comment]
partyId는 제가 정의한 변수 이름입니다. 소속을 party라고 잘못 적어서, partyId 라고 적었어요
