### ISSUE TITLE
리팩토링

### ISSUE THREAD

**Issue by JSDanielPark** [shouwn/graduation.skhu.net-back#49]
안녕하세요. 우연히 코드를 보게됬는데 너무 깔끔하게 잘 짜셔서 놀랐네요.
그래서 배울 겸 자세히 구경했는데 의견드릴게 하나 생겨서 이슈로 남깁니다.

아래의 코드를 보면 Service 레이어에서 HTTP의 스펙을 사용하고있습니다.
서비스레이어는 HTTP의 스펙과 독립적이여야한다고 생각합니다. (비즈니스로직과 플랫폼의 분리)
예외던지기 이슈 하나로 HTTP의 스펙을 사용하여 웹과의 의존성이 생기게 됬는데 혹시 특정한 목적으로 하신거라면 설명해주시면 감사하겠습니다.

https://github.com/shouwn/graduation.skhu.net-back/blob/d94aa5dedb4c5f2169e6322c9a434ca78ff3e1d6/src/main/kotlin/com/shouwn/graduation/service/AuthService.kt#L72

진짜 언어를 이해하고 고민하면서 짠 듯한 코드라 정말 보기 좋습니다.
추가적으로 프로덕션 레벨처럼 캐시를 다는 등의 퍼포먼스 고도화도 들어있으면 퀄리티 향상에 도움이 될 것 같습니다.

감사합니다.

**Comment by shouwn** [comment]
제 코드를 자세히 봐주셔서 감사합니다

Service 레이어 쪽에서 HTTP 코드를 작성한 건 제 실수입니다...

처음에 작성할 때 HTTP 코드가 어디 있어야 하는가에 대해 생각하지 않아, 예외를 새로 만들 생각을 하지 않고 서비스 레이어에 적은 것이 문제였습니다. 

말씀하신 부분은 나중에 리팩토링을 할 때 컨트롤러 단에서 예외를 받을 수 있도록 수정하겠습니다.

-----
지금은 기능의 구현에만 초점을 맞추고 있어 캐시 등 퍼포먼스에 대해서는 고려하고 있지 않습니다.
아직 기능 구현도 모두 만족할 것같지 않아서요. ㅠㅠ

나중에 기회가 된다면 졸업 요건 같이 매번 같은 데이터가 날아가는 부분은 캐시를 사용하여 퍼포먼스를 높이려고 생각하고 있습니다. 아니면 JPA 2차 캐시 등을 사용하여도 충분할 거라 생각합니다. 

코틀린으로 작성하고 이렇게 레이어를 나누어 작성하는 것이 처음이라 많이 불안했지만 이렇게 제 코드를 봐주시고 조언을 해주셔서 정말 감사합니다.
